# Import Libraries

In [40]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [41]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [42]:
df.shape

(569, 33)

In [43]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [44]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

# Train test split

In [45]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [46]:
df['diagnosis'].unique()

<ArrowStringArray>
['M', 'B']
Length: 2, dtype: str

In [47]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [48]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [49]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [50]:
len(df.columns)

31

In [51]:
X_train

array([[-0.05866223, -1.43080538, -0.07558547, ..., -0.2049262 ,
        -1.1850297 , -0.63751515],
       [ 0.03393119,  0.70075412,  0.06527108, ...,  0.31258199,
        -0.33729857, -0.04580515],
       [-0.90883821, -1.6171464 , -0.93741591, ..., -1.24232878,
        -1.21181674, -0.96624292],
       ...,
       [-0.86113857, -1.08084785, -0.89385622, ..., -1.07648754,
        -1.59156247, -0.60518127],
       [-0.4458711 , -0.090059  , -0.41714227, ..., -0.33691315,
        -1.24648232, -0.67254352],
       [ 0.30048801,  2.53462247,  0.45730826, ...,  1.79501179,
         1.85451184,  3.04693046]], shape=(455, 30))

In [52]:
y_train

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1])

In [53]:
X_train

array([[-0.05866223, -1.43080538, -0.07558547, ..., -0.2049262 ,
        -1.1850297 , -0.63751515],
       [ 0.03393119,  0.70075412,  0.06527108, ...,  0.31258199,
        -0.33729857, -0.04580515],
       [-0.90883821, -1.6171464 , -0.93741591, ..., -1.24232878,
        -1.21181674, -0.96624292],
       ...,
       [-0.86113857, -1.08084785, -0.89385622, ..., -1.07648754,
        -1.59156247, -0.60518127],
       [-0.4458711 , -0.090059  , -0.41714227, ..., -0.33691315,
        -1.24648232, -0.67254352],
       [ 0.30048801,  2.53462247,  0.45730826, ...,  1.79501179,
         1.85451184,  3.04693046]], shape=(455, 30))

In [54]:
type(y_train)

numpy.ndarray

In [55]:
type(y_test)

numpy.ndarray

# Numpy Array to tensors

In [56]:
#numpy to tensor
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)

#change dtype
X_train_tensor = torch.tensor(X_train_tensor, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test_tensor, dtype=torch.float32)

#numpy to tensor
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

y_train_tensor = torch.tensor(y_train_tensor,dtype= torch.float32)
y_test_tensor = torch.tensor(y_test_tensor, dtype=torch.float32)

# y_test_tensor = torch.from_numpy(y_test)

C:\Users\HP\AppData\Local\Temp\ipykernel_11484\3826779354.py:6: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X_train_tensor = torch.tensor(X_train_tensor, dtype=torch.float32)
C:\Users\HP\AppData\Local\Temp\ipykernel_11484\3826779354.py:7: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X_test_tensor = torch.tensor(X_test_tensor, dtype=torch.float32)
C:\Users\HP\AppData\Local\Temp\ipykernel_11484\3826779354.py:13: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_train_tensor = torch.tensor(y_train_tensor,dtype= torch.float32)
C:\Users\HP\AppData\Local\Temp\ipykernel_11484\3826779354.py:14: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_test_tensor = torch.tensor(y_test_tensor, dtype=torch.float32)

In [57]:
type(X_train_tensor)

torch.Tensor

# Defining the Model

In [58]:
X_train.shape[1]

30

In [59]:
import torch.nn as nn

In [60]:
class MySimpleNN(nn.Module):

  def __init__(self,num_features):
    super().__init__()

    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out = self.linear(features)
    out = self.sigmoid(out)

    return out

In [61]:
torch.rand(30,1)

tensor([[0.8880],
        [0.8424],
        [0.3298],
        [0.0231],
        [0.1826],
        [0.7409],
        [0.8693],
        [0.5819],
        [0.0319],
        [0.6610],
        [0.3960],
        [0.8169],
        [0.2124],
        [0.9119],
        [0.8401],
        [0.9743],
        [0.8104],
        [0.4631],
        [0.4068],
        [0.5383],
        [0.5340],
        [0.6441],
        [0.6245],
        [0.2273],
        [0.3837],
        [0.4535],
        [0.6882],
        [0.0657],
        [0.4969],
        [0.4806]])

# Parameters

In [62]:
X_train_tensor.shape[1]

30

In [63]:
learning_rate = 0.1
epochs = 25

In [64]:
loss_function = nn.BCELoss()

In [65]:
type(loss_function)

torch.nn.modules.loss.BCELoss

In [66]:
model = MySimpleNN(X_train_tensor.shape[1])

In [67]:
model.parameters()

In [68]:
X_test_tensor.dtype

torch.float32

In [69]:
model.linear.weight.dtype

torch.float32

In [70]:
y_train_tensor.dtype

torch.float32

In [71]:
model.parameters()

# Training Pipeline

In [75]:
#create model

model = MySimpleNN(X_train_tensor.shape[1])

#optimizer
optimizer = torch.optim.SGD( model.parameters(), lr = learning_rate )

#define loop

for epoch in range(epochs):

  #forward pass
  y_pred = model(X_train_tensor)


  #Loss calculate
  loss = loss_function(y_pred,y_train_tensor.reshape(-1,1))

  
  #zero gradient
       
  # model.linear.weight.grad.zero_
  # model.linear.bias.grad.zero_
  optimizer.zero_grad()
  


  #backward pass
  loss.backward()


  #parameter update
  # with torch.no_grad:
  #   model.linear.weight -= learning_rate*model.linear.weight
  #   model.linear.bias -= learning_rate*model.linear.bias
  optimizer.step()


  
  #print loss in each epoch

  print(f" {epoch+1} , Loss = {loss.item()} ")

 1 , Loss = 0.8074650168418884
 2 , Loss = 0.5895036458969116
 3 , Loss = 0.477581650018692
 4 , Loss = 0.4111200273036957
 5 , Loss = 0.36660587787628174
 6 , Loss = 0.3343340754508972
 7 , Loss = 0.309638112783432
 8 , Loss = 0.28998979926109314
 9 , Loss = 0.27389436960220337
 10 , Loss = 0.26040738821029663
 11 , Loss = 0.2489004135131836
 12 , Loss = 0.2389376163482666
 13 , Loss = 0.23020631074905396
 14 , Loss = 0.22247564792633057
 15 , Loss = 0.21557094156742096
 16 , Loss = 0.20935742557048798
 17 , Loss = 0.203729048371315
 18 , Loss = 0.19860121607780457
 19 , Loss = 0.19390533864498138
 20 , Loss = 0.189585343003273
 21 , Loss = 0.18559466302394867
 22 , Loss = 0.1818944364786148
 23 , Loss = 0.17845182120800018
 24 , Loss = 0.1752389371395111
 25 , Loss = 0.17223188281059265

# Model Evaluation

In [76]:
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred= (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f" Accuracy = {accuracy.item()}")

 Accuracy = 0.5915666222572327

# Summary

In [ ]:
X_train_tensor.shape

torch.Size([455, 30])

In [ ]:
!pip install torchinfo

Requirement already satisfied: torchinfo in c:\Users\HP\AppData\Local\Programs\Python\Python314\Lib\site-packages (1.8.0)

In [77]:
from torchinfo import summary

In [78]:
X_test_tensor.shape

torch.Size([114, 30])

In [79]:
summary(model, input_size = (114, 30))

==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
MySimpleNN                               [114, 1]                  --
├─Linear: 1-1                            [114, 1]                  31
├─Sigmoid: 1-2                           [114, 1]                  --
==========================================================================================
Total params: 31
Trainable params: 31
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
==========================================================================================
Input size (MB): 0.01
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.01
==========================================================================================