# Import Libraries

In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [5]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

# Train test split

In [6]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [7]:
df['diagnosis'].unique()

<ArrowStringArray>
['M', 'B']
Length: 2, dtype: str

In [8]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [9]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [10]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [11]:
len(df.columns)

31

In [12]:
len(X_train) + len(X_test)

569

In [13]:
X_train

array([[-0.1517639 , -0.30605891, -0.23598641, ..., -0.94714244,
        -0.90522832, -1.15759449],
       [-0.60260957, -1.05644808, -0.58405832, ..., -0.7376721 ,
        -0.23709133, -0.0268001 ],
       [-1.17934071, -0.94424036, -1.19021281, ..., -1.58385234,
         0.06454333, -0.36193249],
       ...,
       [-1.19397855,  0.49809647, -1.21440805, ..., -1.34764111,
        -0.88252463, -0.15996529],
       [ 0.46888078, -1.22008435,  0.43299082, ...,  0.36761819,
        -0.27601193, -0.70927169],
       [ 0.10878976,  0.54017437,  0.10402042, ...,  0.13863007,
         0.20563051, -0.83411405]], shape=(455, 30))

In [14]:
y_train

array([0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1])

In [66]:
X_train

array([[-1.1152473 , -1.08177193, -1.07914018, ..., -1.18774206,
        -0.82057885,  0.02232129],
       [-0.39495159, -1.40621065, -0.41301068, ..., -0.04314704,
        -0.90894204,  0.05873946],
       [ 0.14249982, -0.39321491,  0.11043404, ..., -0.53950566,
         1.16079582, -0.65169494],
       ...,
       [-0.53901073,  0.67113084, -0.53204827, ..., -0.55695935,
        -1.10266135,  0.35512731],
       [ 1.49720982,  0.44472396,  1.47796343, ...,  1.90891108,
         1.18288662,  0.17359675],
       [ 0.1092554 ,  0.1833057 ,  0.06474284, ...,  0.65193876,
         0.19049999, -0.13007473]], shape=(455, 30))

In [15]:
type(y_train)

numpy.ndarray

In [16]:
type(y_test)

numpy.ndarray

# Numpy Array to tensors

In [17]:
#numpy to tensor
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)

#change dtype
X_train_tensor = torch.tensor(X_train_tensor, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test_tensor, dtype=torch.float32)

#numpy to tensor
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

y_train_tensor = torch.tensor(y_train_tensor,dtype= torch.float32)
y_test_tensor = torch.tensor(y_test_tensor, dtype=torch.float32)

# y_test_tensor = torch.from_numpy(y_test)

C:\Users\HP\AppData\Local\Temp\ipykernel_6712\3826779354.py:6: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X_train_tensor = torch.tensor(X_train_tensor, dtype=torch.float32)
C:\Users\HP\AppData\Local\Temp\ipykernel_6712\3826779354.py:7: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X_test_tensor = torch.tensor(X_test_tensor, dtype=torch.float32)
C:\Users\HP\AppData\Local\Temp\ipykernel_6712\3826779354.py:13: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_train_tensor = torch.tensor(y_train_tensor,dtype= torch.float32)
C:\Users\HP\AppData\Local\Temp\ipykernel_6712\3826779354.py:14: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_test_tensor = torch.tensor(y_test_tensor, dtype=torch.float32)

In [70]:
type(X_train_tensor)

torch.Tensor

# Dataset and Dataloader

In [18]:
from torch.utils.data import Dataset,DataLoader

In [19]:
class CustomDataset(Dataset):
  def __init__( self,features,labels):
    self.features = features
    self.labels = labels

  def __len__(self):
    return self.features.shape[0]

  def __getitem__(self,index):
    return self.features[index], self.labels[index]

In [20]:
train_dataset = CustomDataset(X_train_tensor,y_train_tensor)
test_dataset = CustomDataset(X_test_tensor,y_test_tensor)

In [21]:
len(train_dataset)

455

In [22]:
train_dataset[2]

(tensor([-1.1793, -0.9442, -1.1902, -0.9797, -0.2436, -1.0625, -1.0947, -1.2070,
         -0.3773, -0.3086,  0.0909,  0.1356, -0.0795, -0.3122,  2.5503, -0.7245,
         -0.9494, -1.5112,  0.6236, -0.0960, -0.9246, -0.7089, -0.9628, -0.7802,
          0.8986, -0.9514, -1.2681, -1.5839,  0.0645, -0.3619]),
 tensor(0.))

#loader

In [23]:
train_loader = DataLoader(train_dataset,batch_size=32,shuffle=True)
test_loader = DataLoader(test_dataset,batch_size=32,shuffle=True)

# Defining the Model

In [24]:
X_train.shape[1]

30

In [25]:
import torch.nn as nn

In [26]:
class MySimpleNN(nn.Module):

  def __init__(self,num_features):
    super().__init__()

    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out = self.linear(features)
    out = self.sigmoid(out)

    return out

In [80]:
torch.rand(30,1)

tensor([[0.3545],
        [0.6302],
        [0.8666],
        [0.4654],
        [0.5473],
        [0.2175],
        [0.3748],
        [0.5353],
        [0.5643],
        [0.1711],
        [0.7340],
        [0.1606],
        [0.5227],
        [0.3172],
        [0.6821],
        [0.5573],
        [0.4205],
        [0.8554],
        [0.6125],
        [0.1105],
        [0.4396],
        [0.5152],
        [0.8766],
        [0.1180],
        [0.5663],
        [0.4405],
        [0.5881],
        [0.9170],
        [0.8351],
        [0.2490]])

# Parameters

In [27]:
X_train_tensor.shape[1]

30

In [28]:
learning_rate = 0.1
epochs = 25

In [29]:
loss_function = nn.BCELoss()

In [30]:
type(loss_function)

torch.nn.modules.loss.BCELoss

In [31]:
model = MySimpleNN(X_train_tensor.shape[1])

In [32]:
model.parameters()

In [33]:
X_test_tensor.dtype

torch.float32

In [34]:
model.linear.weight.dtype

torch.float32

In [35]:
y_train_tensor.dtype

torch.float32

In [36]:
model.parameters()

# Training Pipeline

In [37]:
X_train_tensor.shape

torch.Size([455, 30])

In [91]:
#create model

model = MySimpleNN(X_train_tensor.shape[1])

#optimizer
optimizer = torch.optim.SGD( model.parameters(), lr = learning_rate )

#define loop

for epoch in range(epochs):

  for batch_feature,batch_labels in train_loader:
    #forward pass
    y_pred = model(batch_feature)
    #Loss calculate
    loss = loss_function(y_pred,batch_labels.reshape(-1,1))

    #zero gradient
    optimizer.zero_grad()
    #backward pass
    loss.backward()

    #parameter update
    optimizer.step()



  #print loss in each epoch

  print(f" {epoch+1} , Loss = {loss.item()} ")

 1 , Loss = 0.19991599023342133
 2 , Loss = 0.23465119302272797
 3 , Loss = 0.09362495690584183
 4 , Loss = 0.047112297266721725
 5 , Loss = 0.09598408639431
 6 , Loss = 0.02702304907143116
 7 , Loss = 0.09515728801488876
 8 , Loss = 0.031838659197092056
 9 , Loss = 0.092054083943367
 10 , Loss = 0.039030641317367554
 11 , Loss = 0.024209577590227127
 12 , Loss = 0.032057370990514755
 13 , Loss = 0.04334833100438118
 14 , Loss = 0.02426069602370262
 15 , Loss = 0.08535493910312653
 16 , Loss = 0.0920242890715599
 17 , Loss = 0.06778580695390701
 18 , Loss = 0.003728157142177224
 19 , Loss = 0.7356552481651306
 20 , Loss = 0.015241922810673714
 21 , Loss = 0.0015108484076336026
 22 , Loss = 0.058671243488788605
 23 , Loss = 0.1369304209947586
 24 , Loss = 0.024856001138687134
 25 , Loss = 0.11693736165761948

# Training pipeline version 2

In [92]:
#create model

model = MySimpleNN(X_train_tensor.shape[1])

#optimizer
optimizer = torch.optim.SGD( model.parameters(), lr = learning_rate )

#define loop
batch_size = 32
epoch = 25
n_sample = len(X_train_tensor)

for epoch in range(epochs):

  for start_indx in range(0,n_sample,batch_size):
    end_indx = start_indx + batch_size

    # print(f" Start index {start_indx}, end indx {end_indx}\n")

    X_batch = X_train_tensor[start_indx:end_indx]
    y_batch = y_train_tensor[start_indx:end_indx]

    #forward pass
    y_pred = model(X_batch)
    loss = loss_function(y_pred,y_batch.reshape(-1,1))


    #upate step

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()



  #print loss in each epoch

  print(f" {epoch+1} , Loss = {loss.item()} ")

 1 , Loss = 0.19182395935058594
 2 , Loss = 0.13236694037914276
 3 , Loss = 0.10467761009931564
 4 , Loss = 0.08762551099061966
 5 , Loss = 0.07577981799840927
 6 , Loss = 0.0669654831290245
 7 , Loss = 0.060106437653303146
 8 , Loss = 0.054597318172454834
 9 , Loss = 0.050066400319337845
 10 , Loss = 0.04627054184675217
 11 , Loss = 0.04304290562868118
 12 , Loss = 0.04026462882757187
 13 , Loss = 0.037848345935344696
 14 , Loss = 0.03572827950119972
 15 , Loss = 0.03385387733578682
 16 , Loss = 0.03218558058142662
 17 , Loss = 0.03069189563393593
 18 , Loss = 0.02934747003018856
 19 , Loss = 0.028131674975156784
 20 , Loss = 0.02702745422720909
 21 , Loss = 0.02602069452404976
 22 , Loss = 0.0250994972884655
 23 , Loss = 0.024253902956843376
 24 , Loss = 0.023475276306271553
 25 , Loss = 0.022756393998861313

# Model Evaluation (old)

In [93]:
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred= (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f" Accuracy = {accuracy.item()}")

 Accuracy = 0.6001846790313721

# Better version

In [94]:
y_pred.shape

torch.Size([114, 1])

In [95]:
batch_labels.shape

torch.Size([7])

In [96]:
model.eval()  #evaluation mode
accuracy_list = []

with torch.no_grad():
  for batch_features, batch_labels in test_loader:
    y_pred = model(batch_features)
    y_pred = (y_pred > 0.5).float()

    batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()

    accuracy_list.append(batch_accuracy)


overall_accuracy = sum(accuracy_list) / len(accuracy_list)

print(overall_accuracy)

0.9470486044883728

In [97]:
accuracy_list

[0.9375, 0.9375, 0.96875, 0.9444444179534912]

# Summary

In [98]:
X_train_tensor.shape

torch.Size([455, 30])

In [99]:
!pip install torchinfo

Requirement already satisfied: torchinfo in c:\Users\HP\AppData\Local\Programs\Python\Python314\Lib\site-packages (1.8.0)

In [100]:
from torchinfo import summary

In [101]:
summary(model, input_size = (455,30))

==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
MySimpleNN                               [455, 1]                  --
├─Linear: 1-1                            [455, 1]                  31
├─Sigmoid: 1-2                           [455, 1]                  --
==========================================================================================
Total params: 31
Trainable params: 31
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.01
==========================================================================================
Input size (MB): 0.05
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.06
==========================================================================================